apiVersion: v1
kind: Secret
metadata:
  name: site-cert
type: Opaque
data:
  tls.crt: {{ .Values.tls.crt | b64enc }}
  tls.key: {{ .Values.tls.key | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: site-ca
type: Opaque
data:
  tls.crt: {{ .Values.ca.crt | b64enc }}
  tls.key: {{ .Values.ca.key | b64enc }}