all:
  children:
    kpies:
      hosts:
        kpi[1:7]:
    knodes:
      hosts:
        kpi1:
        kpi[3:7]:
    x86nodes:
      hosts:
        ugliv[0:11]:
        pepper:
    workers:
      hosts:
        kpi1:
        kpi[3:7]:
        ugliv[0:11]:
          ansible_ssh_user: jeff
        pepper:
          ansible_ssh_user: jeff
    controlplane:
      hosts:
        kpi2
  vars:
    ansible_ssh_user: ubuntu
