all:
  children:
    workers:
      hosts:
        kpi1:
        kpi[3:7]:
        ugliv[0-11]:
          ansible_ssh_user: jeff
        pepper:
          ansible_ssh_user: jeff
    controlplane:
      hosts:
        kpi2
  vars:
    ansible_ssh_user: ubuntu