- name: Collect necessary data from control plane
  hosts: kontrolplane
  become: True
  gather_facts: no
  tasks:
    - name: Generate join command
      command: kubeadm token create --print-join-command
      register: join_command

    - name: Copy join command to local file
      become: false
      local_action: copy content="{{ join_command.stdout_lines[0] }}" dest="./join-command"

    - name: Copy charts to control plane
      copy:
        src: ../charts
        dest: /home/ubuntu
        owner: ubuntu
        group: ubuntu

    - name: Copy Private Values to control plane
      copy:
        src: ../privateKube
        dest: /home/ubuntu
        owner: ubuntu
        group: ubuntu

- name: Initialize Kubernetes Nodes
  hosts: knodes
  become: True
  tasks:
    - name: Common Tasks
      include_tasks: all-playbook.yaml

    - name: Copy the join command to server location
      copy: src=join-command dest=/tmp/join-command.sh mode=0777

    - name: Join the node to cluster
      command: sh /tmp/join-command.sh

    - name: Add www group
      become: true
      group:
        name: www-data
        state: present
        gid: 33

    - name: Add Kubernetes user
      become: true
      user:
        name: kubernetes
        comment: Kubernetes User
        uid: 1050
        groups: docker,www-data
        append: yes

    - name: Add bullstuff user
      become: true
      user:
        name: bullstuff
        comment: Kubernetes User
        uid: 1001
        groups: docker,www-data
        append: yes
