# You would run this on the Kubernetes Raspberry Pi Control Plane
# Important: Run this first!

- name: Reset All Nodes and Control Plane
  hosts: all
  become: True
  tasks:
    - name: Reset Kubernetes
      command: 'kubeadm reset -f'

    - name: down cni
      ignore_errors: true
      command: ifconfig cni0 down

    - name: down flannel
      ignore_errors: true
      command: ifconfig flannel.1 down

    - name: Clean up IPTables
      command: "{{ item }}"
      with_items:
        - iptables -F
        - iptables -t nat -F
        - iptables -t mangle -F
        - iptables -X

    - name: Remove cni
      file:
        path: /var/lib/cni/
        state: absent

    - name: Remove flannel
      file:
        path: /run/flannel/
        state: absent

    - name: Remove cni config
      file:
        path: /etc/cni/
        state: absent

- name: Reboot Raspberry Pi and pepper
  hosts: kpi1:kpi3:kpi4:kpi5:kpi6:kpi7:pepper
  become: true
  tasks:
    - name: Reboot RPis
      ignore_errors: true
      ignore_unreachable: true
      command: reboot

- name: Reset All Control Plane Extra Steps
  hosts: kontrolplane
  become: True
  tasks:
    - name: Remove charts
      file:
        path: /home/ubuntu/charts
        state: absent

    - name: Remove privateKube
      file:
        path: /home/ubuntu/privateKube
        state: absent

    - name: Remove .kube directory
      file:
        path: /home/ubuntu/.kube
        state: absent

    - name: Remove certs directory
      file:
        path: /home/ubuntu/certs
        state: absent

    - name: Reboot Control Plane
      command: reboot