- name: Apply Helm charts and kubectl yaml to control plane
  hosts: kontrolplane
  vars_files:
    - ../privateKube/admin-values.yaml

  tasks:
    - name: Apply Administrative chart
      command: >
        helm install administrative ~/charts/administrative -f ~/privateKube/admin-values.yaml
        --set-file tls.crt=/home/ubuntu/certs/voight.org.crt
        --set-file tls.key=/home/ubuntu/certs/voight.org.key
        --set jenkins.user='{{ jenkinsuser }}'
        --set jenkins.password='{{ jenkinspassword }}'
        --set sonarqube.password='{{ sonarqubeadminpassword }}'
        --set sonarqube.postgresqlpassword='{{ sonarqubepostgrespassword }}'
        --set postgresql.password='{{ postgrespassword }}'
        --set dadcloudsql.username='{{ dadcloudpostgresuser }}'
        --set dadcloudsql.password='{{ dadcloudpostgrespassword }}'
        --set elasticsearch.username='{{ elasticsearchuser }}'
        --set elasticsearch.password='{{ elasticsearchpassword }}'
        --set openldapconfig.password='{{ openldapconfigpassword }}'
        --set openldapadmin.password='{{ openldapadminpassword }}'
        --set kibana.password='{{ kibanapassword }}'
        --set grafana.password='{{ grafanapassword }}'

    - name: Apply storage chart
      command: helm install storage-nas stable/nfs-client-provisioner  -f ~/privateKube/nas-values.yaml

    - name: Apply Vault chart
      command: helm install vault hashicorp/vault -f ~/privateKube/vault-values.yaml

    - name: Apply postgresql chart
      command: helm install -n devops postgresql bitnami/postgresql -f ~/privateKube/postgresql-values.yaml

    - name: Apply jenkins chart
      command: helm install -n devops jenkins stable/jenkins -f ~/privateKube/jenkins-values.yaml

    - name: Apply Sonarqube chart
      command: >
        helm install -n devops sonarqube oteemocharts/sonarqube -f ~/privateKube/sonarqube-values.yaml
        --set account.adminPassword='{{ sonarqubeadminpassword }}'

    - name: Apply Selenium Hub chart
      command: helm install -n devops selenium-hub stable/selenium -f ~/privateKube/selenium-hub-values.yaml

    - name: Apply Selenium chart
      command: helm install -n devops selenium ~/charts/selenium

    - name: Apply fluent-bit chart
      command: >
        helm install -n monitoring fluent-bit stable/fluent-bit -f ~/privateKube/fluent-bit-values.yaml
        --set backend.es.http_passwd='{{ elasticsearchpassword }}'
        --set backend.es.http_user='{{ elasticsearchuser }}'

    - name: Apply fluent-bit configmap
      command: kubectl apply -n monitoring -f ~/privateKube/fluent-bit-configmap.yaml

    - name: Apply ElasticSearch chart
      command: helm install -n monitoring elasticsearch elastic/elasticsearch -f ~/privateKube/elasticsearch-values.yaml

    - name: Apply Kibana chart
      command: helm install -n monitoring kibana elastic/kibana -f ~/privateKube/kibana-values.yaml

    - name: Apply OpenLDAP chart
      command: helm install openldap stable/openldap -f ~/privateKube/openldap-values.yaml

    - name: Apply NextCloud chart
      command: >
        helm install nextcloud nextcloud/nextcloud -f ~/privateKube/nextcloud-values.yaml
        --set nextcloud.password='{{ dadcloudadminpassword }}'

    - name: Apply phpLDAPAdmin chart
      command: helm install phpldapadmin cetic/phpldapadmin -f ~/privateKube/phpldapadmin.yaml

    - name: Apply haproxy chart
      command: helm install haproxy haproxy/kubernetes-ingress -f ~/privateKube/haproxy-values.yaml

    - name: Add sonarqube database
      community.general.postgresql_db:
        login_host: 192.168.137.72
        login_password: '{{ postgrespassword }}'
        name: sonardb

    - name: Add nextcloud database
      community.general.postgresql_db:
        login_host: 192.168.137.72
        login_password: '{{ postgrespassword }}'
        name: dadcloud

    - name: Add sonarqube database user
      community.general.postgresql_user:
        login_host: 192.168.137.72
        login_password: '{{ postgrespassword }}'
        db: sonardb
        name: sonaruser
        password: '{{ sonarqubepostgrespassword }}'
        priv: ALL

    - name: Add nextcloud database user
      community.general.postgresql_user:
        login_host: 192.168.137.72
        login_password: '{{ postgrespassword }}'
        db: dadcloud
        name: dadcloud
        password: '{{ dadcloudpostgrespassword }}'
        priv: ALL

