# Important: Don't run this unless you want to delete your entire cluster!

- name: Reset All Nodes and Control Plane
  hosts: all
  become: True
  tasks:
    - name: Reset Kubernetes
      command: 'kubeadm reset -f'

    - name: down cni
      ignore_errors: true
      command: ifconfig cni0 down

    - name: down flannel
      ignore_errors: true
      command: ifconfig flannel.1 down

    - name: Clean up IPTables
      command: "{{ item }}"
      with_items:
        - iptables -F
        - iptables -t nat -F
        - iptables -t mangle -F
        - iptables -X

    - name: Remove cni
      file:
        path: /var/lib/cni/
        state: absent

    - name: Remove flannel
      file:
        path: /run/flannel/
        state: absent

    - name: Remove cni config
      file:
        path: /etc/cni/
        state: absent

# This part stands alone because I'm usually working on ugli and I like to reboot it myself
- name: Reboot Raspberry Pi and pepper
  hosts: kpi1:kpi3:kpi4:kpi5:kpi6:kpi7:pepper
  become: true
  tasks:
    - name: Reboot Nodes
      ignore_errors: true
      ignore_unreachable: true
          command: reboot

- name: Warn user to reboot their machine
  hosts: ugli
  tasks:
    - name: Warn user
      command: echo "Don't forget to reboot!"
